# Generated by Django 2.0.7 on 2018-07-27 06:39

from django.db import migrations, models
import menus.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, default=9999.99, max_digits=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to=menus.models.upload_image_path)),
                ('menu_type', models.CharField(choices=[('meal', 'Meal'), ('drink', 'Drink'), ('snack', 'Snack')], max_length=120)),
                ('active', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
